test_that("H37001: samples, subjects, variants, expression", {
    skip_if_no_token()
    db <- test_db("H37001")
    expect_equal(nrow(samples(db)), 6)
    expect_equal(subjects(db)$subject_id, "H37001")
    v <- variants(db)
    expect_gt(nrow(v), 100)
    expect_true("BAP1" %in% v$hgnc_symbol)
    expect_equal(names(v)[1:4], c("sample_id", "measurement_set", "variant_id", "hgnc_symbol"))
    expect_equal(provenance(v)$db, db)
    gx <- gene_expression(db, genes = c("BAP1", "GNAQ"), measurement = "rsem-normalized-count")
    expect_setequal(unique(gx$hgnc_symbol), c("BAP1", "GNAQ"))
    p <- plotly::plotly_build(plot_vaf_histogram(v, samples = "H37001-001"))
    expect_length(p$x$data, 1)
})

test_that("tcga-uvm: cohort shape", {
    skip_if_no_token()
    db <- test_db("tcga-uvm")
    expect_equal(nrow(subjects(db)), 80)
    expect_setequal(dataset_summary(db)$assay_technology, c("WES", "RNA-seq"))
    expect_gt(nrow(gene_expression(db, genes = c("BAP1", "PRAME"))), 100)
    n <- do_query(dq(find = list(c("count", "?s")), where = list(c("?s", ":sample/id"))),
                  db = db, cache = FALSE)
    expect_equal(n$count_s, 80)
    d <- datoms("aevt", list(":subject/id"), db = db, limit = 3)
    expect_equal(nrow(d), 3)
    expect_equal(d$a[1], ":subject/id")
})
