test_that("prince: measurements, clinical, context, plots", {
    skip_if_no_token()
    db <- test_db("prince-2022")
    mt <- measurement_types("PICI CyTOF Immune Profiling", db = db)
    expect_true(all(c("percent-of-parent", "median-channel-value", "cell-population", "epitope") %in% mt$attribute))
    pp <- measurements("percent-of-parent", "PICI CyTOF Immune Profiling", db = db)
    expect_equal(names(pp), c("sample_id", "measurement_set", "cell_population", "value"))
    expect_equal(nrow(pp), mt$count[mt$attribute == "percent-of-parent"])
    mcv <- measurements("median-channel-value", "PICI CyTOF Immune Profiling", db = db)
    expect_true(all(c("cell_population", "epitope_id") %in% names(mcv)))
    ol <- measurements("olink-npx", "PICI Olink Proteomics", db = db, wide = TRUE)
    expect_true(is.matrix(ol))
    oc <- subject_outcomes(db)
    expect_true(all(c("subject_id", "bor", "os", "os_event", "pfs") %in% names(oc)))
    expect_equal(nrow(oc), nrow(subjects(db)))
    km <- kaplan_meier(oc$os[!is.na(oc$os)], oc$os_event[!is.na(oc$os)])
    expect_true(all(diff(km$surv) <= 0))
    tp <- timepoints(db)
    expect_equal(tp$timepoint_relative_order, sort(tp$timepoint_relative_order))
    ctx <- add_sample_context(pp[1:20, ], db = db, include.outcomes = TRUE)
    expect_true(all(c("subject_id", "timepoint_id", "bor") %in% names(ctx)))
    expect_s3_class(plot_survival(oc, group = "bor"), "plotly")
    expect_s3_class(plot_by_timepoint(ctx, group = "bor"), "plotly")
    va <- variant_annotations(db, genes = "KRAS")
    expect_true(all(va$hgnc_symbol == "KRAS"))
    expect_equal(unname(map_gene_symbols(c("p53", "HER2"), db = db)), c("TP53", "ERBB2"))
})

test_that("H37004: CNV (subset required), isoforms, interventions, matrices", {
    skip_if_no_token()
    db <- test_db("H37004")
    expect_error(cnv_segments(db), "subset")
    expect_error(cnv_gene_calls(db), "subset")
    cs <- cnv_segments(db, genes = "TP53")
    expect_true(all(cs$hgnc_symbol == "TP53"))
    expect_true(all(c("measurement_set", "contig", "start", "end", "segment_mean_lrr") %in% names(cs)))
    cs2 <- cnv_segments(db, subjects = "H37004")
    expect_gt(nrow(cs2), nrow(cs))
    iso <- isoforms("TP53", db = db)
    expect_true(all(c("transcript_id", "isoform_percent") %in% names(iso)))
    expect_gt(nrow(clinical_interventions(db)), 0)
    expect_equal(nrow(measurement_matrices(db)), 2)
})

test_that("painter: gene-level CNV calls on spotty data", {
    skip_if_no_token()
    db <- test_db("painter-2025-angiosarc")
    calls <- cnv_gene_calls(db, genes = c("MYC", "CDKN2A"))
    expect_true(all(calls$value %in% -2:2))
    expect_lt(length(unique(calls$sample_id)), nrow(samples(db)))  # CNV only for a subset of samples
})

test_that("provenance survives context joins", {
    skip_if_no_token()
    db <- test_db("prince-2022")
    m <- measurements("olink-npx", "PICI Olink Proteomics", db = db)
    ctx <- add_sample_context(m, db = db, include.outcomes = TRUE)
    expect_equal(provenance(ctx)$db, db)
    expect_false(is.null(provenance(ctx)$basis_t))
})
